apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:D0btsO/Zz1BYdTYoNJ70kReK70jCvx6ozzz18EE=,iv:Z2zgaSO5o48kgOig8BjqZkPyjoY9zdL3uI8nmSWfMBM=,tag:Dj4EVdoMTzGPi8TWuP3agA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSWkybTNTRGdrU2RzVW01
        OVAxYlhtc0hGcW1jMEw5bUMzMm9ZSmRpSmlnClVadFNSbkozTTRLODBoTWtJYnhl
        RTROb1dQc05kcC96cm14V1NXZ1BYakUKLS0tIDlFQWQvMXAvZUZUQkNmeU5Hally
        eDdrTnhpb0RjUjlOdVp4ZC9sbnBwS28K1kdxfP1zm/pHc0fzzq+jNRQe5AJhkHLf
        MQyO8IpW7Hl8YSTcSk3rCOYvsIq11OQy0K9PLvd5CJoqXSaYGBKUlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T10:47:43Z"
  mac: ENC[AES256_GCM,data:jRZkhBZ9j/lCZ6mrnCpLS6oDJG4+PgNVCbdbulTMs9OpKg6qD53F/RHc7hePxk72JKaZzXU5w/h9eOT0BO+oKKj4UK1+Jy8Ezxm6VIU7IcYf0OwmHIPjIgNZGuTlmX6k25IX/nszjSUHm4OtSzitH9PkWWz/6usBbRiEUEk9Ahw=,iv:1ykM692UZbbyXIGtI9yZA1rH919ovHELoJ+iMjls2jM=,tag:SQ7O6BXmsNkvlmwrEHG27Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
