apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:S/SB4KqvRbZfqYkaNxBeJLE2Ve/ThQKgkn69qpZ5r8VjlTogiQdo1g==,iv:YZtBhvaOnwXFU7MbKdanGZf2bFg6LdJZWsl9whAYRQ8=,tag:lu+10tFZCvwdzxyNnAl4Jw==,type:str]
  client-secret: ENC[AES256_GCM,data:p15bFSIOJ2cHiZ6YCg2RzBwPkTficTIj4k1DUuMkkySfcd0aABtYaCSU/orFB72crFupeAiON1KKVgbim+/uvHkicTw0Hx0oqiMIEUjrNyZPHzuOHL65KOQ8ZvoCfUiLW28qCmfpqgwjbrufmlC0qCWAgX7T3zvC/XmW8Y/nmSc=,iv:gD9mrQ4KcIghhoD7zFGYS/bpaXi4CPND0cVdUKDbFN4=,tag:RyX8TFk/ly5+tEDY7e8Mjw==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejJhRitqM2xWRHp4QTBG
        Y2VpNjQyNmpQSlJqTDg5NU5TQ0FJQVlXTmdRCnpseEtpeUh2c05rTXl5cUwrSndr
        aEs2YU1NdnI5OU05RHBOZVhJbVY0dmMKLS0tIDArbkNDZkxiRHBhRnV0Mi8zMnRD
        am5maFJDRUtoMFVzNWdrR2cwZFYwV2sKGYWTSFvtTeUbHNZ/4gdhQOHuzQ3/S9tc
        +exS6R8HibM0Nqjf/RAy3uMGRystCDLwFRvPLhj+b5cCV+jwDI3Y0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T10:17:46Z"
  mac: ENC[AES256_GCM,data:vHNC/pc0M4x2dEgHbPcQPNj8R4E4rmCDThYq/17QDEZvjnoO3NAau3WK7y47FXWIlNL3K3AYRI3s5iOr5sj0jkp4m5Dga0kgHuQhonbJ+u4riJF3Q3iQYfTydXFCiKd04TdP2+SpfZhuf9evKNr9QJ/qEUCdl5Nfe//kQjIrS9A=,iv:ZUiU0pG1GWQOaNrp1I5ToL447fNbo5BytoTyELe3chs=,tag:RqNkfV1k5vwvxDih2F1RVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:ozpkALMyBECNSrbpWbSUNIlDzSx9jgbq9aqXZwQ=,iv:ML7Ovrp4MTp3paGYNjCekVIUdCUJ53E8VPLTaqchxIE=,tag:fKbtAr2twGcj5iSSNoOYsA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejJhRitqM2xWRHp4QTBG
        Y2VpNjQyNmpQSlJqTDg5NU5TQ0FJQVlXTmdRCnpseEtpeUh2c05rTXl5cUwrSndr
        aEs2YU1NdnI5OU05RHBOZVhJbVY0dmMKLS0tIDArbkNDZkxiRHBhRnV0Mi8zMnRD
        am5maFJDRUtoMFVzNWdrR2cwZFYwV2sKGYWTSFvtTeUbHNZ/4gdhQOHuzQ3/S9tc
        +exS6R8HibM0Nqjf/RAy3uMGRystCDLwFRvPLhj+b5cCV+jwDI3Y0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T10:17:46Z"
  mac: ENC[AES256_GCM,data:vHNC/pc0M4x2dEgHbPcQPNj8R4E4rmCDThYq/17QDEZvjnoO3NAau3WK7y47FXWIlNL3K3AYRI3s5iOr5sj0jkp4m5Dga0kgHuQhonbJ+u4riJF3Q3iQYfTydXFCiKd04TdP2+SpfZhuf9evKNr9QJ/qEUCdl5Nfe//kQjIrS9A=,iv:ZUiU0pG1GWQOaNrp1I5ToL447fNbo5BytoTyELe3chs=,tag:RqNkfV1k5vwvxDih2F1RVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
