apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-firewall-bouncer
  namespace: security
type: Opaque
stringData:
  BOUNCER_API_KEY: ENC[AES256_GCM,data:Q05spfIlMQ3Fd2BaplqOhAiUzWTs8p8/EQlRmF/nlHFHMPuYMPBSv78t6g==,iv:AajLMZBc7jO/vL3jU2Z2PQpHBuXuec7ejeNBhh40L6g=,tag:wqIqNdHszgrRBjxc7AwdiQ==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGVUUnJYeVBDdDR1aUpY
        Mk43bDdwUVc0RTBtajhucU5sR3FVSyttbFFRCjNSWjUwT3lhUURRRk1GMWJFeURO
        WnQxN1RJRXd4aUV2V29PRFhWYyt6QkUKLS0tIGtlR0s2WUc1UG8wVzNaUWttVDQy
        cU1ZNC93M3NJL2VIWlpNL3dSMWc0bjQKAuyN/jfU57pP3hi1AWTKUl9F4UnXP3Ks
        Ydfqk1GDUl31z4mg8wbVBnL1tHFrG7O5GJSGAbPrfbOYAHg11mOy9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T17:10:19Z"
  mac: ENC[AES256_GCM,data:ejrQ9D+++KBKzYuWzTHBcbMXRhVBJx9jzz/m4pis8s17w2mu0Bi39JUdcELTpbuTGhwsT4QGriajvI26BGEn7A3vJvpUeiYRNDky1VrrQ0JfPlpiQe6Fk4uq7rJtKzdEM1Fg1P5uFcmreBgzI8fRgCnoM2kYvDP6XMuX1rhhhlQ=,iv:E0mxlJFpiRFk6ojcY0xxHbH1P6lhTMsuD6g2FMI/AI0=,tag:B6udOkFnoXLN0HGI0YeYVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
