---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./notification-config.yaml
  - ./firewall-bouncer-secret.sops.yaml
  - ./firewall-bouncer.yaml
  - ./envoy-parser-config.yaml
