apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-keys
  namespace: security
type: Opaque
stringData:
  enroll-key: ENC[AES256_GCM,data:wmBrHYFV67NKMgvWVi0aAl7sUjxKJDXKmg==,iv:ozpUhh66ebn6GvgXLWgSggKvX2Ky3F+TnSTQW3ahPOY=,tag:f9zk431yjZTx9mWXgOLnyQ==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSTJMSWtheXFQc2U3Ylkz
        MHdPRndJbmZ0TXpSbmN1ZmpROGtlSnRWWGp3ClFTbHVXT3BzVHIvOEZLOGNEcnda
        OXFoN1FlakpFMU9IZUsrRFZST2p3WVUKLS0tIFA2aUU1WXYvMExjVnQxV0NTM2tM
        Y1VwTEtjdWNWNStQZEVUeFFlSGlpTjAKQ58GmVuFc37SC8KNzpvhtZpQEIyZxO4K
        6mkv0Stq6CV5HqS7xLL5E/L52/ZS2kIn+pe2MPgCluR3QrEuRzA8+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T14:52:59Z"
  mac: ENC[AES256_GCM,data:d5bzQulpM1WhR63CBKYamWAPKSlcjPGl0QmZG14IIEaaRnQi+eiqi7kScQ23maEt0tumg+LXMLjuAR/KHIZ4Wypv0RjUcAYVBMhJDyGOvhLzBGa90G03yDrqcVy26HX7yqQGyjns9RYYJvR3aFl5+vlCII2+dGvP4QH/tuaPBro=,iv:rt/JjGJxwR6lrYDDcXl0c2rAvD2tFAGajOyQcYuP/ao=,tag:h+ZbxVnozVJ/feN/bTLRzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
