apiVersion: v1
kind: Secret
metadata:
  name: coturn-secret
type: Opaque
stringData:
  TURN_SECRET: ENC[AES256_GCM,data:jorF0VwOb5GilgdERzS4TVJoX0rUy/mKMSZOb238kMtdXVpM47KiWYJgExs=,iv:TzSjdOfM+pQkIIq0KzD4G9TGZERQfhF4Iy63bTBc6ls=,tag:9KRS+AMXiz3udhjyEPzdqw==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYUVLOEIwOXA4NDFzdWZE
        V3lQUXE4SGJwNktrZkI5am4wZW5hYTNzK1MwClYxN1J4VGJaSllJYjFWaFZFeHFC
        cWRMTUxTU25wRzduUnA2anFRNFdualEKLS0tIE9zKzJYVDdiZ0E2a1NCdTB5S2hT
        ODlDZlc1Q2pMQVVJZlhqanlwMFZ5MjgKUWmaB6be3D5hYg9S0NQ6GLG468dKFDhI
        FY9ZkfyXU8YeYisZqpnAn+oIZ5J8pCB7Dq4Wg/fGhwFIQ+4M+eRQHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T15:06:20Z"
  mac: ENC[AES256_GCM,data:mrCtHdlla+7U9TLNf9ZKIQ3VxiBXyXYthIBw1U+NIysW4o/WG1z/jpFp94rEUlzo50AR7yDkuVVE1kU9j5NZ22nHqHxmAFGuGI6YVaiR8QqX6iIhX2tFRo9KOjN9nbAnuDRLSVvc04OMRUQhVPdLM3f/BtsejTDX+U1w/DzCHA4=,iv:HxjyZnKI+6qRLWwUTadG54FUqRGJmWI9cQam3D2fwZc=,tag:wwiPPA9x9bnphuV8GIsgjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
