apiVersion: v1
kind: Secret
metadata:
  name: coturn-secret
type: Opaque
stringData:
  TURN_SECRET: ENC[AES256_GCM,data:gUCWj3v3wjqzXWwNCISCwRy27mpjGz/UEX5i4NHYTrwFwSczBq8KtRH2clk5dEIx,iv:1/BgyfaQ27EJCyIKL172Qs0tkYzI6PHmAGZZcPtpqLA=,tag:CdIgiv2l08O0wtLGCkDVmQ==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYUk4STFpN2t6YlQxblVJ
        VmdRSkNVSGhtZ1ZTcVBFSlF5cXJvOGRTVFZNCkpaNHNzZ1NMNGtjdzJqRHRsZjA3
        S255RVZSTzhiY3RYUnNaTitCQWRCczgKLS0tIEZ3V09sZUNyT3QxWFdYU3U5TUFj
        TWpKd2ZvS1VVcEluclRLMzcwdUkrRlkKdWwS8bYXuJeLcsLQYjMObbXoEFFl9NSt
        GEAhBpdy8B8OSINvg5YwWjOVGpzcJWxcy82Reyzc99V9/3qcisH7Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T19:58:42Z"
  mac: ENC[AES256_GCM,data:PKuLMaYKyrkYoPRakGQe5/9nbHTYA0O3h99PPQei/vDh3NpIFzQA8K3tbNnx8YEYkNIEZL3W/RUyCRQgmQ1GDjKDVqAmQnhpO8eWOea7CWkP7ddfKKoiCFirfTZVHN414Pv4H+xqU+gjfVAaSzjgvONKqv1gQJYtRX7+KpxOwUs=,iv:Y9y/+hWDfCP78W/my3I9a9Pp8eViHcHne1f7ONubYCs=,tag:Cu7jwpThABmbKFSBc+ZHgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
