---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./postgresql.yaml
  - ./onlyoffice.yaml
  - ./coturn.yaml
  - ./secret.sops.yaml
  - ./coturn-secret.sops.yaml
