apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-secret
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:PvbH6xLV0KtY4KakfoSy+ZNNeXsTcTXNeTmQQ27NRAR13+OcIf2KDpSLtF4=,iv:n2hi/ZA40jp0LSKqPo/+jGEVfi6FlsZ2f+Rp0n4iAME=,tag:o7xwY1JfoNSzrVzzjh3Ukg==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUDB2RDFhWEFOdXd4Mks5
        QUw0TjRUeHRQdXdFUy9tRjBaeEVCVitMNm1nClc3Um5mbFRHUytlRnBQSkliYjRn
        WUZaQ3NyNHFXZ1BoMURHamFhMVBpaDQKLS0tIEEvK1c5T1V6RDI5dFJCZE03Y09h
        UGhPMzBPWVBZeTRTcmNrdVFULzNrQzQKG9PAoi5UsSpem2jazRvoUI3kYyPi1c0X
        5DKkLWIe9BkH61sXoPYnQ0jgSlFUiq0Gy3rYMFlne+fSlJaLWiMH5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T10:50:12Z"
  mac: ENC[AES256_GCM,data:pcYh2j6TKUM4H2aHiYm1GaLh+u3W4EPCN4gDrvxEFPwFBOz9eIWEALDFkyI38WNQDfrY1GQoQz2P1Zw3SGzUD+OGhAbTwy4X/gmehnwfgM09ONozXefPjylkNIkHtp2x4gDfYCPe5eHfr5z6lgVQRiF5L+JpUvcjQkiIWFAGk8s=,iv:HmnvcAIlv124SqoGNra/ifS1XuGC45KRVk1BfQRtDe4=,tag:Rw1JsjXEi6+L1vOp9UAJng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
