apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nSlpWESYdk0ZBtrVNrVjjgC4+C6u6zKHZFluAkcM1FiyK9blEisAmw==,iv:swmbew4Z7hu4+8+Ik040EnpSLoXtI1yhfBkmHbaUo8A=,tag:xblKHoDV5R1dKolROOzk3Q==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNUsvMHZNMis5K2E3YnZy
        dmNUM0xya2IzcWx5TmkzU2xhTTduQ0JLV3hNCkVEQzluWG1XSEdIY1MxbWUyZzlL
        Qi9rSm9yMmFtNEN6ZWlTeFhNYnBOVncKLS0tIFRtSExGVWhzc2d6bnhRR2FYRnJu
        NjFLVTVKYXVLNnVySThVUDgwdjhuaDQK8sJ4qM2tRir+MF64VS/l+EdA5PULf9Ru
        y3LIGw5f1eU3B4A4IjJcgpNfKJYdnUXU0VqFRQ5bsWcDiLnfgrvIEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T15:20:42Z"
  mac: ENC[AES256_GCM,data:VihwW6pB1XzYzPUtU1Mx24iTLGxZhDsvgp/IGHWzwStv3oQls85rNgtmHd42aLlKQBtOk8eG73Jmpgs+zOybkpBRxY9AIAZSdh+eck7s6/QMInYc4gp3EX9M7eIrRiYk0EDhucGlAIiHOdRQQKx4uR3ZGWS9mWru2v4PLPBfyvI=,iv:8qhSn/hZrnupVQfKeLI5brICOkJQRUIPjC7e27OLCBE=,tag:lVLPGgPlqCHV/NmeNqLLQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
