apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ailQ8RJzR6cKbhxCY2uz5x/fuuO07OzhP8NdNsLzWSZXlZ41rbpjxg==,iv:53NBof3JYDCi+r8lOxBr8En4d5UGGdzuvuuFq2g8n14=,tag:+V/pyADTZksnKoHGe+qWtg==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa1BQdjZ4TFhNaEsyaExL
        Z2k4aGJyaXB5YzFPT3p1ZFlWL1FuWkR1ekRvCnZIWElGUjhmNVBHbitzOUY1MEw0
        Si96bHNYNGVVc21XTGUyQUlNQ1J5aHcKLS0tIFcvY0s1V2xRNlBLbW5pdzYwZlBH
        YlB4c3VHemlsRzA1WEdMTkxKZkF3Qm8KuTa39t8RnllZPMrPMqCwxEUtxxkcpIf3
        SoGGk9wv2FtOTLyWjX+6+/ffmZKdeUMoefm2vecm5ePMgyovBHShJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T14:09:46Z"
  mac: ENC[AES256_GCM,data:baQvnX441LwvN5Cc8ESKWQrnIt2kKA+f3X1ZUvcC7rv6uI2GFSCewqI3Wa+ieuIDgMMJ6rAJyMKXhWtNNVTkRlXs9KuZ8YW5kgIvyxypBO6Fo1gpi8RVsR68ZC83lDqzTBU/xCLejguuFQ4X1mjhHQWUY3uZe/jSWRNCL7WMiDQ=,iv:BvKNvijTNOIoZE9fm9jaC9R5nNP9+5lK2PPeOUunCd8=,tag:tWOShXJAgujyYQImugzitg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
