apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZnMogl/9mgV8//Wj9T0=,iv:V9uLgMSNghRvmn93YwPTow8WSj+eiyNRIH4KuizePIU=,tag:zOg5MycpMHW4EgGOrUKreA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y2VTelJaZlZVTmEySFpH
        Q1lEVlRMMEJjVWVMdlhnVWdUSEJJdVYzWms4CnMrVWdhdEtTTlIxMkVEWC8rNnBu
        bXlLa2ZQb281Z21tckd4YUd2VEtIOTQKLS0tIDZtK1FKVlNFckhaczZHcXZub1p3
        ZjBRWVZpZkI3N1ZZbTA0YlEzcjF5bWMK5uMIFWqqdkfJNZhiuCQCy5+mhtptMNeB
        s1wDgWpMA49U+H2LHfaljuuZTPYjor3hqEhCqnp/QKQjna3FOPfKBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T14:09:46Z"
  mac: ENC[AES256_GCM,data:0+Kkr5xehcKf+sdYwaeC24+Y2QCut9mM4ZQas81gv0v4FIK16Em3DdNbmwUsRnhRCUnz4bc1Iz7Il20G2my0OEoKz/NzA/ItShnaczRA6hvA53I3SmShASMKPggo6M9p/C4nwSeUqWQg4TEMa1+89y5xhkeAko6h57b0iiL5rN4=,iv:kPcRn9yAXJNd/rAtkkObTZM9CUoE8zqr6SRAePV4lfc=,tag:RoQGYBl/r7mEjs2A7SappA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
