apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:U+ePvfBm9gpTRw==,iv:oZxzAb9trFAtg1zMkq9AI7QmPmM9glIQ2t8sPCkMTt8=,tag:JbbIy7jHxvMXPCvx5hRdmg==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVXJjaFVmYXNMZzJ3SFho
        NmpGSmxZRitTN2lVbm45dnJ2VU1yV29icUYwCmtSOFd1ZHhvOTBKTzR4K2pTYlpl
        cVdVVFNreDgvMEpyQmcvU0s1dHYySDgKLS0tIFhSNmM5UVJUcmNRRFd6UVBTUzRW
        bFcvMXZFdlp2NG5VM3FnaDJRaU1MMlUKEFIpuN2UQVNLnBldXSF27v/IXtcrTwTs
        dUVaLnc3oeFKno3zZ/+7xqEqSNvCoEmU234TKfCfHns8+rPH9jjr0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T15:20:42Z"
  mac: ENC[AES256_GCM,data:1Jkj5Qqvt/l4dcxmv/EETTyCUAtWZcvJuvxjKNLPigshBz2tKr825d64lTh7Wg/Ir6HH5KAd9eGxlLoVSS8Lvknwcb4PKIjUfsHMLvZWNQR5eFHUHtNEDiBYLC75s93pad49FdQWfmjjd912lNXjUT0r4sLvq0WDYokdPflf+RI=,iv:TkecR4vk62QM8ahmBDS0q9BHxMTWBT+qF6sjJFQPK58=,tag:EyHXLfuUilXU5AEgDnxi7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
