apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XeSlGbsNO6Ih6dK5nJngI/LIE854YndFpogJYBkypXg=,iv:yo6LLH9nBc69MQh2cQpTRENCGN96mJ0j89420cblzTE=,tag:U/5hKs8oiyT51uyMcCqCbA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VEdnOFBuQmgwRkxVNUJN
        anROWWsyM3JLSlhwVDgzT3F6dWlHOXYvOWpZCkF4bHowR2YyNnZhMVVNK0gvdkR3
        YkZvczBUUjhaSGZZMGkzODJMZ1pmdkEKLS0tIHBuaitMT0hhZ3NVenoyZlp0bnhu
        N081UVc1cTNjR2U5R3NxNGl2WWdGUlkKwRhsNsWutbU2/jv2iLrhsdGv8fvUsMt4
        m89dS/PK01RxxVRmWSGGm3c2RHP5tPSOm9bxrUEn/9lax5j6liUffg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T15:20:42Z"
  mac: ENC[AES256_GCM,data:A0Ad9YYX+oKQsmQTcmQgHOaKfbvnwf7Q0WJhjV4I1CZWvxPEr44V8MC6wA/VdW724dQfKsDMt9ntVtPVPrLkJ+dT/63lvTqL4cUf5FNO6pxgpJTRSUzwI1HaOCiT754y0kNIPcMQJeBNSMiQV1ojQgnUGkSasEM5D7sBdx5UysE=,iv:JCuAJrrk1LpTTfHW3YbUspg4wPPwxI5LPMzgF4qTxF4=,tag:orreV/439AbnmANuxaE9IA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
