apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ewaS46sLXsAtkpZKNIbIi0IKLWU7HhesFnYA7V9qQns=,iv:vvN2QGMO8ahPTtoq9egdLPTB1e3Qm+Rl4edtOZXmEaY=,tag:8/jZsHGvZ/+GP/8/B0rVVw==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMFVlV29YdklCRFI3RFVt
        a0tEcU4xbVhTQVVoNjBxbEJidE9NQS9BUmlRCkZCRW9TTlY0WTlxS2lhQUhYMGZN
        VXJPVlZqTWM4U0llU01za1NCQTBad3MKLS0tIHQ4VlJyME9QT2JSUHY1SGUvVm5W
        UG9iVE5FWERmNHFpZWl1dys4RXFTUE0KtfIcVn88b5oqORN2A0La2v6OdHHLjmB0
        zOIQryVoBWfB/g6PEygikWQGi/OKQBD9QgRpc3i/KpW4szG5A+jBKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T14:09:46Z"
  mac: ENC[AES256_GCM,data:7wDfADMkqGTtPKKEd5/ngab0fpJeO2OPzxpEltOEsR1aSqAZVxRYKb2wWOkriytO4NuPkEPPJNqLQavN4dEa42dOf1sa15kCgY9AGPO9YaArEyFlZFLzXZUS2zERXshkWogIhdT2qZ8PChSAlsiRRqc2Nt1WFKPQ7eRT/dGdMIw=,iv:K3ksU6NBLQZi381gvkxKLek03K5WQ7UwtokJj/XLsyw=,tag:GSGnA/9oLfSZijGOPY9YwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
