---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./rbac.yaml
  - ./configmap.yaml
  - ./secret.sops.yaml
  - ./daemonset.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
