---
apiVersion: v1
kind: Service
metadata:
  name: nut
  namespace: kube-system
  labels:
    app: nut
    app.kubernetes.io/name: nut
spec:
  type: ClusterIP
  selector:
    app: nut
  ports:
    - name: nut
      port: 3493
      targetPort: nut
      protocol: TCP
    - name: metrics
      port: 9199
      targetPort: metrics
      protocol: TCP
