apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-ntfy
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:spCNcuIo+X5SDowTj6HHiJaPMxtdE4kV4LoANNYpUN8x2eyh6u1jdw==,iv:SHQ6Mg6H7iz7wiQ+/r4guor3K1TaFZZHQaaLUxoCLUA=,tag:/haLFreDQQzX0+MydxOu4w==,type:str]
  client-secret: ENC[AES256_GCM,data:WoErznhiogUGrANZMo9CEFGPFymc76EHk7+zmqK7FK6HJydzaoR54sZJLbxjtuaFRgY0MXnczbLIk39Tih4W63cs0uCdFf5rU9heEVafb8Kwzg3AzApc+pYJhieKb34HF6vGxz+VVoQTLtLX/iP7vBs8I0fWL+kd7HuLgVrQJxY=,iv:BKuCCtYYkfjadfppwxNNNw9bfok4XT6PLIHEZx8uq4g=,tag:Mpr/PqLECWlYfUv8m//lNA==,type:str]
  cookie-secret: ENC[AES256_GCM,data:SbBIj6/BtHF3GqEUS1REyKd+D2+Ts29bqRp0xNM8/wKNN9biCDNraP0Ry6k=,iv:w51XmWRpOCL7x3DisshOC4xYX/nSeky3Pwaet7gCAnA=,tag:2v2k8iwjHNTiSgjwUfpS0Q==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQlFZbUw4U1RIUWxuTTdM
        OFRqN2lST1BueWFxWGtzMFpBUnNYaGsydVdNCnlsZEtrQjBVYy85NzNkT3pEbVlR
        VFFCemZVM3VzR1h4b1ZGN0U0VXpRd1UKLS0tIFVEUGNOOFM2eHlJVEkwRUt0dnZJ
        cFFUN0t6T3c0S2JVbjlHZUlZdTdHbHcKB4hoIi/iSZALkEhPOx1DL8b+wDYxk8H0
        4osUhNZUFniUaGfNZfNsoux4BYz5dMlm5wvK84Xhaevf/mn0UzxefA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T21:37:14Z"
  mac: ENC[AES256_GCM,data:sILnCRGN4pSji891bfnwCA9cnV7UVIuU2Fpoj46Y3pLO27pMyreSk81XIt307cF4JBYvBXWRoqKHn9+XKbDojRTSt7rf9EQgxBIt3A9BAuEwjpQONkeM2TFIk4Smo22/FyS8Eitcl8Mue8C/I69MdbUZhWxpxVTzZ6zTxq2ed3A=,iv:RI+3hLJlBHCD6b3qXNav1hb+qdqCmMVy/ZSyo+kULX4=,tag:ypy+SquL4X1SA1Br5LfJ6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
