---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./immich/ks.yaml
  - ./nextcloud/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./bookstack/ks.yaml
  - ./ntfy/ks.yaml
  - ./oauth2-proxy-ntfy/ks.yaml
