apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:n55QpoT9gEs+qrpThDGotxKIKH33n/KJlCgId6u8tPO3F4ZNxPN8OXum52KZIv7xdfV7IEquS0U5xqzsHKNuqy1d5kE04Erj1dMYLilmQApWg0V6jbGYDx85xcsU2/dEMSMTrrkCvXkqp4vvYf9sKKKOSufuOByxOIhrPD90Ksm+/FYJxmuRYv7Kz4cqwNgQ36HgI4MQ3Ue1IH12FVXjM8lac+TR7UaLIO26fB42A/9MVEqp,iv:a0/zLiDpmf2XfDOVcj+oigI+IYYzGdraz+KJh2plCKQ=,tag:ztMohQbD4Tn0d/SR3eF5NA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdmt6bHZJL1YxNm5oMjBV
        Szl4bEpMYVlEeWdGbUp2cmFUMXI2b2swdkNVCkpocTZNWHB5TEZXOUVFa0o4bENO
        YXlYK2Rtc1Y0czNqU1dpekhqR09jaEkKLS0tIGIzOUVNaEZzUDlKS3lOcU1ZTFg0
        ekV0UDBab2d3ZGxDWk1hMTl0TkI1ekUK2QPifv+8XeePfFr20rsBW9pR/ferWxKp
        zKVGqK1juGJTkVce6FG16/HXJOMvg+1ZVYJ24JsDD71LazRosjgJ8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T15:20:42Z"
  mac: ENC[AES256_GCM,data:tI76vQCaymW7uLi+v/AVWXRlR8VqIE0wWipK9/wcHs2nOw++e3o5dwgsZ/5qlQ6/jTT+W/qTSkQLFj/JV3jWFIcvdLo0wOnXXFtmJcuKARVCyak4dX8cXW5J6/Yx7E5+n3zR2WnJIqeItUtz6MzWWiHIDt3bEInaa8PhJ8y6ygk=,iv:qNRW6ufIzo6zKfBf0/zAnn1I1iP4+dTCn0I0f/3tl0g=,tag:4USs6U9u2ymwBiYPnFN2Ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
