apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:4if+WK/Vak/KtdGXUPfdwn8ZeUWt+2T9KJXPGU5yvhp69gbDNYuS+d2MwHNOVKx4pNEojepNeGCP3ahKKQ5wstF51zCTbcBKRpCXS7MEO6J1Rskcty50Bn1paIbMkEJHBD3ABm+O1OAgrnhZQnbXmxxt6AiTBgQ5+KzyfW3eRpd8vXAIAXTyzBYwdLT2FpwCCVjSZ52vDDUFnmsBFl/mz7ArE3BY8zvJH8zQpaGUuhscJndM,iv:F9YkueqU5ECbwvFrFHkKvPfrxVaAY/DLZO/nbLJxq/U=,tag:B++wbFKoo++/w1+hp6ZgnQ==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaUFOeUpzS0VKQzRZT3hw
        Q2hWMlE5RndmWkMxYjVJRXEzMjZZUFlrWmxBCkVYZ2RvK3FaOHIxN2dFbERnMFAx
        ZzB4UnM2ZUs0eEFmSkNXQTFPaDFmVUEKLS0tIDJwSVVJWks0b0NiM2VXU3RCbXU2
        Qmdza2VqTmprTXFOeXBBSGtmN0lySWMKNtFDNZVRRBa4nWWqYNu3abJQsPL3j8bL
        /DgOHiY4ErHPUv6/a1pIyZeLkGjrBq6hmX2r8vS8Eyk1/TOQl8h6Rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T14:09:47Z"
  mac: ENC[AES256_GCM,data:yT7uHgyvEPnSJiW9GZlkZpLQGm6vJ5RIkfbNYyCpLvNSCEcY9VzMbVr1IqNEKPGAzfNFN0+w98yL9oXMu7TMdxz+ao+JgqZK8mJ+O0FUrQRksCICHUekIavAlzNa8GFnhdou7h9RjaO+gvrL48a7TZ/WfeAQX1yQ3BRw6OBYlIA=,iv:iQQNEvLWpd3HYpEhi1CQ+DtbLr8Mcb91t8pTIW71qkI=,tag:90KGTqCmW+yU0H7NT8mN/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
