apiVersion: v1
kind: Secret
metadata:
  name: bookstack-db
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:oHBrl2quBvhWOJLSZVkXNM+Nnp3agVTTOJNXJdvlUos=,iv:g/BtoihLFnRtXUZ/gdzek1IpD+SK0aS79VAlA7y3ur8=,tag:fULZDmYzYvxTzQsEZ5fp0Q==,type:str]
  mariadb-password: ENC[AES256_GCM,data:LHev2ffdcx2oguF6Kgn9i+JYUWYbPkCIEMLyUyBKO9k=,iv:0Avh6osUiMh9p6kXjoBp2IaUtPbCjsCGavJWEPBIDW4=,tag:THdnqIVlEc3Asl9/5yiURA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOTc5MDR5c1dDSzRWbTFx
        VzBHN1BnTWtPTlR0M1RPUkRWMzFNUFF6UkFzCjVsSXU4L0tQdzBVOWxqRzJSTFdD
        NlM1aG80Qm5jM0F0Z3dESHE3ZVJ4VVUKLS0tIE9UdDFkSVpKcVBmT2s4Z083M2Zq
        RFpoOXlBc3FRYzY4bGJlRzMzTXJxL0UK9dh5NFSTe5i2c3WHV0XTsCEARruj0SQ9
        RqXMlnu2j+7oNFp4qpFHar75cabKw21SbHxKq1rtADcVMXsudreRRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T14:45:13Z"
  mac: ENC[AES256_GCM,data:9x9WfuQgvEAzhcO9hWNd6AX28EirKfLrI6Diz1TfxDhOK7WSwhvPuSJCiSjLdyhBwKiiSJHJTEOttrvdtQFt8wkdRg6MN9nW7zqowtRx/PYFgR5DYXDpJwN8/d2l/wNhsx+kAu5V9Vc08n5+MdBLRYu82qPV6LigxUEArpEYp/E=,iv:nrTggqF4LiazJapmSGCqrZcYvKDYZ0TaF65h3wU7jNM=,tag:AZ4JVaEwF0zaPr7DbcY1ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: bookstack-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:HKtawkpi4wq5xmn6G7uwBs5MowyWoDvsOKwvY5a2+/47A6eYKoY1pQ==,iv:OnWQpHMtjQQVP/MzNLLFkgsrUzi/ueyD6LJah5q1bNg=,tag:jlFARgJkjrPZmSSQDaZ61A==,type:str]
  client-secret: ENC[AES256_GCM,data:cQzTrXeVESq0IPvfmG62J72C063Rfn+fNnBXC3FUi6mUdpEoBMlnT2MOgeWA3HnFmGrimTW3rqscbSxtV3zJxC0p0SvMBHhsUGrhdNZSwTEyT9CtJV3idryeqe2MYUXr2A25cSB5nfo0KqMKvvQXNbNcCVCRpoaNJyIsApPT9y0=,iv:nnDCIAkcR0E5arS7YA2OzB+2l7lZEPPNcZB9NALCSco=,tag:55MTKUpB0+Kl4/TT/Vrh8g==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOTc5MDR5c1dDSzRWbTFx
        VzBHN1BnTWtPTlR0M1RPUkRWMzFNUFF6UkFzCjVsSXU4L0tQdzBVOWxqRzJSTFdD
        NlM1aG80Qm5jM0F0Z3dESHE3ZVJ4VVUKLS0tIE9UdDFkSVpKcVBmT2s4Z083M2Zq
        RFpoOXlBc3FRYzY4bGJlRzMzTXJxL0UK9dh5NFSTe5i2c3WHV0XTsCEARruj0SQ9
        RqXMlnu2j+7oNFp4qpFHar75cabKw21SbHxKq1rtADcVMXsudreRRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T14:45:13Z"
  mac: ENC[AES256_GCM,data:9x9WfuQgvEAzhcO9hWNd6AX28EirKfLrI6Diz1TfxDhOK7WSwhvPuSJCiSjLdyhBwKiiSJHJTEOttrvdtQFt8wkdRg6MN9nW7zqowtRx/PYFgR5DYXDpJwN8/d2l/wNhsx+kAu5V9Vc08n5+MdBLRYu82qPV6LigxUEArpEYp/E=,iv:nrTggqF4LiazJapmSGCqrZcYvKDYZ0TaF65h3wU7jNM=,tag:AZ4JVaEwF0zaPr7DbcY1ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
