apiVersion: v1
kind: Secret
metadata:
  name: bookstack-db
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:2lYHfPOl7HdD1BERhOx2Op/DbNc/dfRkUt35c4U3V+c=,iv:gZU0t1AjR+HTtZKZp7+h7SGaEBVuy2B9brHu0aLWBpU=,tag:/hY/MD70aYMzIpMxEL2S2g==,type:str]
  mariadb-password: ENC[AES256_GCM,data:/CjVaECWa4eOX1FZEWVaOXPAeE6897i6mi8dNkpZuao=,iv:O+cVJJt3Joi5/1Zg1o93YedQQa8sN55QMoXMLQwAZFM=,tag:L8niKqiylrpaO2JM0vniyA==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:70Cs6K+1EqmJQE6jrLyk9Zd88jUPUudnrS1QU23aZdw=,iv:32nIqeY84+RyEijmTnwMtMLJI4PotUneir7SHDU5tME=,tag:Mgr8SijUUrC8c4jIZRbb2A==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMm92SGZJbTd4OStrY0xP
        VnYwczZzL0FNeEluMWk0aElXUHRVd29NQlJFCm95ZzBTd0RNZGRubjVDbWxLdTFY
        SGV0WFF3SVhoNVJRQTZWK05nU3MzNFEKLS0tIFZYU25YNy8wY0ZmMkVCakhWZ2lU
        aE8vanplVjl5OXUxRUtya3E5a21mcTgKMnWUQsFkMUTsSuQK90dgfde4K0zhg1bv
        LczkFnDpsA7WvIU8agMAcr2v+TGepkPIPgzDGkb7NPY6BQouyOQzOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:03:17Z"
  mac: ENC[AES256_GCM,data:6u/ZaxKEs9u/DtYK9mKvPuZ1jKhBEEEfKVXCnMx0i19zXIYaYf/V4ilziR33xdSV0weADZ1pNd22nijxGkccwAtQcGgAgIOIO9gFU0CWDFoAhmDEAfxi2sepWTJCezIm3/cb1aYlRHYdueDw2SNGW+Z2GPF6IZHab2jIdKqAhhU=,iv:j7sD592mJYHIutYJEbOPVcs3RdUnCRQm/SLqmItTr1M=,tag:wibqaY87ZRCx3Fi8wOpoPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: bookstack-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:DBmI9P4u/iYLEnpUYIp91UqX61MRVTHYDbk/ysznBJT0xfq3JVV9NQ==,iv:1HfAXQqtKVeGKYrYsuaXMVaJ34plkxifqmH9P6rhAXs=,tag:X/bp932e0UL/35S57eDnIQ==,type:str]
  client-secret: ENC[AES256_GCM,data:JS3+KjebivbJDr6fWcR5roIF4YE8flRKQXRH51oRH99x6OrEbq8tIYTrh3s26JHQr2Mh3nnnkecxEGpSQXflBkb+SVJjUDNlchrmRGEllp529dxLqHP4GaQJoFgJhwyRBSeyVz59qjZRyeqnQ43K5yXQGtaOYfhUu/e10k4aVPU=,iv:6w4HECcC9XN4MY0oqereXf/pwL860ekMqzlkU6RU2YI=,tag:4ZRmHnq4cBLTpzuuew3IJQ==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMm92SGZJbTd4OStrY0xP
        VnYwczZzL0FNeEluMWk0aElXUHRVd29NQlJFCm95ZzBTd0RNZGRubjVDbWxLdTFY
        SGV0WFF3SVhoNVJRQTZWK05nU3MzNFEKLS0tIFZYU25YNy8wY0ZmMkVCakhWZ2lU
        aE8vanplVjl5OXUxRUtya3E5a21mcTgKMnWUQsFkMUTsSuQK90dgfde4K0zhg1bv
        LczkFnDpsA7WvIU8agMAcr2v+TGepkPIPgzDGkb7NPY6BQouyOQzOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:03:17Z"
  mac: ENC[AES256_GCM,data:6u/ZaxKEs9u/DtYK9mKvPuZ1jKhBEEEfKVXCnMx0i19zXIYaYf/V4ilziR33xdSV0weADZ1pNd22nijxGkccwAtQcGgAgIOIO9gFU0CWDFoAhmDEAfxi2sepWTJCezIm3/cb1aYlRHYdueDw2SNGW+Z2GPF6IZHab2jIdKqAhhU=,iv:j7sD592mJYHIutYJEbOPVcs3RdUnCRQm/SLqmItTr1M=,tag:wibqaY87ZRCx3Fi8wOpoPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
