apiVersion: v1
kind: Secret
metadata:
  name: bookstack-db
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:6GpGouef0bQpS3q8Y/Dlecp1oO3lgd0Y/YRHIicHCns=,iv:hj2yi5f3BpW0gTBUPUegaK8sN8ouMHxJhpBF8LC8DOE=,tag:MIhwXGwGQwglI8QfmUZpQg==,type:str]
  mariadb-password: ENC[AES256_GCM,data:zkT09+e3VKDNHeKk6mQc1VRpirtE1k1a3e6VFVufu+0=,iv:+mHwf9rIn8Xe3qIirWMmu9UVydhKTQu52X5LyOrqVmg=,tag:yRegmLi+HpUKOB++F07dJA==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:3UboHu874HTUWNWI89GzANDz6g80zfsxoC0pJG/d0LU=,iv:3hmS+SJIveepS1SKKpy+Lvc4EC6nZKhcDiPC1CepDu0=,tag:SvAve3UetLpWWjl0lG4DmQ==,type:str]
  APP_KEY: ENC[AES256_GCM,data:lNVQUBDZCmWoXuEL5nkG2nzBMazLham5907sy9BtlF9X+pdWDS+RBzYf/Kz0cMNT938a,iv:e5o5h4uyohp1RohBpAOU017tcViqSBzHnALDGYtO+Bs=,tag:uiQrwGL9FWbu9FR3R13jjA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RkZDcEpQZDY5b003MDAy
        enFYY2pUWnhWamhUZmcwRTFxSVY1Z2Flc204ClJjSWZFOXF1cStuWmh1OVV4Yllu
        M3NMQ0dCczF6ei90ditEa3lKZ21zZ3cKLS0tIG9PRDdwRFBxaThzb3N2R2ttTG4z
        VUFCcHZFR1BxS2ZSM2VyeVdrY3hMcWcKJp90PHlk/xfvK+6Pd8LEgUTSSg+W7jbD
        vq0WGzjyDc60Xs0worsqNqnVKfVXwEo6F8QhSCE/0YgrG5L9Y/Grnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:51:26Z"
  mac: ENC[AES256_GCM,data:oQYQovffAypSPoDJ7iSnzE160zw7NMRGnzfJ5jl4iip6Xq5JqVzue84NIh6RnL+14fw/FKLuG3GkPrHdmfhmf6Q0aCDYEoLwrWHUIIGl18p9M8sDNI6tNqDW3Mmxscm6E5VtN3kWnm//4WKfvryDIyTdmfpvKCdQ6+xhZeweeM8=,iv:yox4jyGN7NNIjDcloDCLerfKL7kBnN8nUUUmscNc+W8=,tag:6N3cvkwukBikwfu/YIhdyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: bookstack-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:Pr2eaxKVF86Z9XAbG9rm7+gLIEeVtLtgXI+g+H/X8+GU4Edj5GvPgg==,iv:kS7HA7gdzu1dqQFfNmUgFFoJzj7XF/f5zBU+GNV3N5U=,tag:h61ztIOnn382c9NUcwekjg==,type:str]
  client-secret: ENC[AES256_GCM,data:xmNlnS1QKp5cV6TDQOkH+CyCOBC92L5+Pw2OViXw5XIgTdlppYQLAmghLVFQkxpdTUn+uRxvOIVVv+ZXLpPqWF5xyrtujvv5AZAZ7sPT4ybGv1f192QOLktEL/G0dbBZXGV2QWp4YK/cHGJ9c46IUKkBRo6GcWngJ6I4fxSj2l0=,iv:Xc4DCB2VqbR7M9NZ2rM1IRLECWXwMvsy3jvl2JHNSl0=,tag:DGCSzOCI8o9WEpH8N21s8w==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RkZDcEpQZDY5b003MDAy
        enFYY2pUWnhWamhUZmcwRTFxSVY1Z2Flc204ClJjSWZFOXF1cStuWmh1OVV4Yllu
        M3NMQ0dCczF6ei90ditEa3lKZ21zZ3cKLS0tIG9PRDdwRFBxaThzb3N2R2ttTG4z
        VUFCcHZFR1BxS2ZSM2VyeVdrY3hMcWcKJp90PHlk/xfvK+6Pd8LEgUTSSg+W7jbD
        vq0WGzjyDc60Xs0worsqNqnVKfVXwEo6F8QhSCE/0YgrG5L9Y/Grnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:51:26Z"
  mac: ENC[AES256_GCM,data:oQYQovffAypSPoDJ7iSnzE160zw7NMRGnzfJ5jl4iip6Xq5JqVzue84NIh6RnL+14fw/FKLuG3GkPrHdmfhmf6Q0aCDYEoLwrWHUIIGl18p9M8sDNI6tNqDW3Mmxscm6E5VtN3kWnm//4WKfvryDIyTdmfpvKCdQ6+xhZeweeM8=,iv:yox4jyGN7NNIjDcloDCLerfKL7kBnN8nUUUmscNc+W8=,tag:6N3cvkwukBikwfu/YIhdyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
