apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-longhorn
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:ZNw4xn7kt+RI9geyj7FnxsY4J/gKPx7gg1fxc8u12aeG6CnuUHESoA==,iv:BVwMKueBFcXzqdIuU+17ZdbNU7zuSTmkt82N6q/A3+E=,tag:9rQQx7DsnCDnJLaVbEPTZQ==,type:str]
  client-secret: ENC[AES256_GCM,data:uuCiS5U+ThqRqH5R5locpyv4NXyH+b0L56nIoYd/qL6TK7UrNTA/2TaMRlohXKfzMrmWdqT9oRx3TmLL3fBgX02vZXqKPtb8IiiGvgIRcELO8fu0q62b9aHNG63RIDC7TtSIQD944yjDGkI8q1lDv+38AV/0tADrNRbvKJaUhiI=,iv:qacBw/P3igtOeb7tiFSINAq94Z7Yk6sZud3VBqEVcZA=,tag:el1HVV6FMoBDIaSfhdhX4A==,type:str]
  cookie-secret: ENC[AES256_GCM,data:o6fSeni6ElUgoq6t0izZ4Ly4lrRDN8Z6,iv:E8VC9sbDheWe4jLhHdNk5epFJvv4fQcWvTUgSOITA74=,tag:vS06ZEN0rwMa+J4G7dC6TA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQmZacDRjRmNLSEhLb0h5
        VER4WjhNWG50K3ZVTFJtZWJ5SnlicmtKREZVCm5pRmNKejh2ampDL0tVV0Q2SkhZ
        Vk1DRk9INWV5bGxMbnhXd2IvZ1JLYjgKLS0tIDlCUVNNL0h4TUFNSGhxS1dDQmxY
        ZXRPeW9BaXovZDQzdHFZSFpHZFo5amsKfOwNSTT2P+jAVspoIDRAPOq4xpB3h4c8
        o+ymk8RUbZH9sJeGiKByysmFQyw+zCjy1mnQ0L+dBtcqwgWcStMihg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T23:02:57Z"
  mac: ENC[AES256_GCM,data:GIJjED/BRcU/Ta17snhJlx26s6g2fdZ6lfPpw5ayGoNxa81qQVnQinDur2mruLycpaE46GJ8Xn1XUf5sVs5unaj6659g2X/+ID5XvCOct5Gcxq1crGzAyGizBF338NHkFevSJHK4V6/zmJ3D1W+T9IiDK6RgeWDTLwZNWXzAYlg=,iv:oRJabCZU4ClodBN1iK+rMbiOVGVZFALNFyZoo7BDm/g=,tag:qrZ1mdBf2kgrV0S4aGjnFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
