apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-longhorn
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:kBuX9NZeQPkMML1qDEFT8/+yGaEzV/OecB4TtH0ZB0e8s7G/+D3iXA==,iv:2Ytk7y5+KURHC4YKkEQ0SU9r4Z9Ta/epo82Jf8IdeMs=,tag:5eIsO/OQKJh71nZdB0W+jw==,type:str]
  client-secret: ENC[AES256_GCM,data:OHmZoMcSaQ0DfZ+TIq+Mb6d9yB+ny0A+Pe75dWY1/C3zHHY3ZXASEi5lYSR4O6R92ezE/4M8iNjxtBOTUY+GaHcq2E2nbPlvnyHj3zFA7jsMEb5hXDbEqhz/nPh0kfZ++l2tJ6wly7e6drBRAT4XyKZICvDg96bXeXkfCA6OuEA=,iv:zLOL4LuIFDYQnjK78gnSUaZZsHWa+br5GH5iEwE85Mg=,tag:SM1sRJ2ZfXMvw+XzTh41Rg==,type:str]
  cookie-secret: ENC[AES256_GCM,data:/nQiYGNnQEJnY480rc3WaPkgqc7J66GtQMSPYfwcZDpKp4xZohjCLY7UWck=,iv:2HmCf2YVixemjMmJuIVweQvnZAIUWF6POk9X4VgroE4=,tag:WSxeL3qGhI6Bsk2F6fusjQ==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSWZyTmZlcE5hanN6N21k
        OUVhU0VzS3VxZk53WlM3VGpRSHF0TXljM1Y4CnNvTU1MQWFLOGREZjZsL1NXRFVy
        aW5pb3JoTms2NXBydzJZNnpGalQ5OWsKLS0tIFdFdjdrSExRcC9GNlBEZERQL211
        OEY3SGNsWGxETittLzlwYlJhNVVaOVkKHa2FOjPH/DV8pucqW2vXf5Jh1/sNfve0
        lIgRrQKcL9HcZ+mRLIEE3n/JV6z5P8VVo2yKZRFg2dbpy9w9WYJgPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T17:55:50Z"
  mac: ENC[AES256_GCM,data:zg1zk8Vp3IPCBdqczddII6NBeQ0o+jtP967UwHQYDG9J1i3bzRpGzOvTXadCfsTwsFMRmpKj6LbwfX8gB+OOEnl/A0SNJuZSBcqjEkkwZ1mxAv3PHl0v9RtzY7atCHQYW4GfFTGssupDIEvIJE1FgwgF5CaXlgXvLy6Z5wIBX8w=,iv:cwTTtmCCzTeB88/XMbdIQlFq+F+efxnL8wttIEun8CQ=,tag:uYFdvR2sd9BWxwyGwomEXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
