apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-longhorn
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:TlcDO0+A0gbSZayuSGUiSnXkLXTDlo3jdqOgav3KpbjDIaOE6j3THw==,iv:MtDz9LmiGoypag/35QRABmainjPmO6Vt5npU/aMCYac=,tag:fCZgHrnlfRPsLD7DpQY/tA==,type:str]
  client-secret: ENC[AES256_GCM,data:XsYqxnF+AyIbn3H5k4LCAWTl6/bL80WhvOesxzO96DvnL9LSCPRFt0icSwIvETbzm5B3+DL1Gwp4912DxYACOBxLCugPY3+VI8t7wQwlIOKJIw6+WuaSo2EeP8Hkkb32CF7fZlUEcDlUYOzG2YzS66mrb230MjSw01dZ2mfdtVo=,iv:2P7Tcbq1yZl8P4Gt6v/3mM0zRCs0IaH7hPMgT2nJ6JQ=,tag:a4k4+pEMacEVr/C2imICag==,type:str]
  cookie-secret: ENC[AES256_GCM,data:jYzwKu1oY1QE4QIwvCxKTxTXAruoG98+KdhbRunCVL9RzZIO2M2+k9Nf9mc=,iv:Kpjb6EXPJORY9H/966T9kbQBIs4pdUAJ7SNtJHgBik0=,tag:mCqiaW6hs7yZJ2VJ+/kUsA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV2RuYldMenJsZjI2bFUy
        U3pxNmJMcVptOTA3Y2xSUXJxZWk3OVNZV1NJCnhQMXZEQ2JOL1BDa0FVTElvY0FF
        NGlsZ0MxM1NJdWIwYlFPNnhXOGZjMlUKLS0tIC9oR1EyQVdYVXhsZU56c3FwTCsy
        U1NHb3AwblpTRjd5ai9nRW9zeVAzeEUKn5lCMTNqF+Vi2idgF0y/SIEP0L9D/nQK
        x3JrwstREc8hjSiMAG7/UJ3wOskixUzGJIMR/13g19QNqHR+1BQjjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T20:24:29Z"
  mac: ENC[AES256_GCM,data:JXQUFZJ6dVY9sdzV8qmghSafDlx0j4t7udanTN9RSbAnN6HiKnLouB5g8zgN/eQfxAB/dc42krAhTksWV/B2xWL4bVYHE4tEXiIk6MfQ0gk4+HfwWqVpnatzTpMIrOQvLCdn3dvxp2pUyiFBGX17Dkk3pGC+SkfRwHju+3XnQVA=,iv:9mIS5V39Ts1VnyjX+RrLAcCrEiYiJMRRR8wBrY6UpbQ=,tag:1zbu+inAgTsunVd7Ih39QQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
