apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nmC2r0GP4TWMqEePLzR7bLRVXNhZiPgh4bvia5LT+zXR41mPCUk2Mg==,iv:cQIT3PjwyZcS+m/2VXWd9zQjfVbLj0TRKlFPNO+khLc=,tag:O68cbJWKxtT/lEzb82zNMA==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbldVTmRNQjNLZDRObXZX
        dlRZOEhFc1JrempkRmpSSGlsSFN5bExUbVZ3CkcwSTRmT05JKzNMTDFyaVpxNisv
        akUvdGhYQnhYNk0wTXhqNmdpbW1KcEkKLS0tIEE1cm5PZlJRakY4N3A4OSt0WlFh
        ZC9tVG1sdnBjd2hjMmluWFF3N2pNb2cKHuG5YlRXHdors6mnewQ+tGfqyVMDUf2F
        s0kChVBU1Bb1nlEGTbq2Y9fJONr6GR5470QO9uAmA5qk4fSjb1jf9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T14:09:46Z"
  mac: ENC[AES256_GCM,data:lj/ERlDxO3/0ZYc9Bs9DiMowG/xvhHxz6tRUU4n2ORuBMtIHnu2tU744OFAEeM3sBGw4UxJuQyxUvh9Dq7xvym04KP5j3wTw0i8vcaU65/Nxw4ewirzYKQkmlUAIjWNE4WJ3r0zpdjyuVp4MHzANOnb9Gp5OU5I5gLYn/4yMqsM=,iv:t6aUldu7LqvIAJ5HnE8b2+EonKx3pPxz9yTp1vg5MBE=,tag:LYZ5HWvSdC66yXGelI2LkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
