apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:g2oQaqoGq8khJdk4xb8DWnAkbu6S5jryVi+vCkdhpsJqZ/Zf/3UDmA==,iv:JZ2PEdbmawX5NmcU8UkC5zXiiAaJHA+VT4xlLbbabvs=,tag:hPe5IwZIDKvfPiNzBr3Dzg==,type:str]
sops:
  age:
    - recipient: age1rhp2xf08fczha5uhwp8xr5sw3kwka5qemhkx7qc9l0g4s7sv550q92jkgd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ2I3MFJGaTA4QWMyMldR
        M1ZzcDBHMjBJOTBZMW5jSTJJV2NoekVueFIwCkl4bnNuVE05eDFVRWM3YnA2Z2tR
        Y0grOExNTHVaZFlNN0d0VTU5NGU1UGsKLS0tIENLcnlGNHNEWURtVytoTU5EYXR6
        RC9HaGhIYS90T21hUHRybmpRN1NiMjQKmvsXeHIAWWtriV8szCy//jbcX8yUwPXF
        P/36c7IDTU5T6QR5l+LkH0doyiu9fcvaNtHe0qwAkTu7ymc28LXf/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T15:20:42Z"
  mac: ENC[AES256_GCM,data:tpuU+3TVtnKe2javcOHWq5Yo0l5xg4GJSbu/BaqCLm9aFqnbPsSmZldcBMDf9GPvcN/BayoDT6ALGFUbm3LcNeLqpT2UvqKMn3ONLjzouDE1COpB1oPorDhT91G4IiEb8pU1o3B/PGpUS8gpzdaVn4e13D22bqDWDaOfISCdXU4=,iv:xFDRb08PGei2PuCTJY0z1bE0TzcPuUlaj0iE2/xRIfs=,tag:1t56Sxro7kWJaVQjKm9rgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
