---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-manager
  - ./default
  - ./flux-system
  - ./kube-system
  - ./longhorn-system
  - ./monitoring
  - ./network
  - ./portainer
  - ./tailscale
  - ./security
